channels:
- conda-forge
dependencies:
- python=3.12.12
- pip<=24.1.2
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.2
  - psutil==5.9.5
  - pyyaml==6.0.3
  - scikit-learn==1.6.1
  - scipy==1.16.3
name: mlflow-env
